export const baseURL = `${import.meta.env.VITE_API_BASE_URL}/api/`;

export const apiEndpoints = {
    LOGIN: "auth/login",
    ADMIN_ME: "admin/me",
    ADMIN_OVERVIEW: "admin/overview",
    ADMIN_READERS: "admin/readers",
    ADMIN_BOOKS: "admin/books",
    ADMIN_INVITES: "admin/invites",
    ADMIN_INVITE: "admin/invite",
    ADMIN_ACCEPT_INVITE: "admin/invite/accept",
    REGISTER: "auth/register",
    REFRESH_TOKEN: "auth/refresh",
    LOGOUT: "auth/logout",
    GOOGLE_AUTH: "auth/google",
    FORGOT_PASSWORD: "auth/forget-password",
    PASSWORD_TOKEN_VERIFICATION: "auth/password-token-verification",
    RESET_PASSWORD: "auth/reset-password",
    USER_PROFILE: "/profile/",
    DELETE_PROFILE: "/profile/delete",
    UPDATE_PROFILE: "/profile/update",
    CLOUDINARY_SIGNATURE: "/cloudinary-signature/image",
    NOTES: "notes",
    NOTES_BY_ID: "notes/:id",
    USER_STATS: "stats",
    BOOK_STATS: "book/stats",
    BOOK_START_READING: "book/start",
    BOOK_END_READING: "book/end",
    BOOK_GOAL: "book/goal",
};
